### ISSUE TITLE
doctrine datasource

### ISSUE THREAD

**Issue by Lopo** [romansklenar/nette-datagrid#12]
v pripade doctrine datasource sa retazia filtre takze vysledny dotaz je nezmyselny

riesenie: https://github.com/Lopo/nette-datagrid/commit/6939044f9e5a7baf0cc60f0e7821c1d98ba03908

**Comment by Majkl578** [comment]
https://github.com/romansklenar/nette-datagrid/commit/9d90a80a4e70e5834f7a67010afa3d9d7265af68 cherry-picked
