### ISSUE TITLE
Pass param from tempalte to component

### ISSUE THREAD

**Issue by armenmargaryan** [romansklenar/nette-datagrid#14]
Hi im using old nette-datagrid v 0.9.4 - https://github.com/romansklenar/nette-datagrid/releases/tag/0.9.4

Im initializing datagrid in template in following way

    @{widget` driversFeePaymentsGrid}

and grid defined in presenter

    protected function createComponentDriversFeePaymentsGrid($param)
	{
		$driverFeePaymentsManager = new DriverFeePaymentsManager();
		$grid = new DataGrid();
		$dgt = new DataGridTranslator();
		$grid->setTranslator($dgt);
		
		$grid->bindDataTable($driverFeePaymentsManager->fetchDataSource());
		$grid->keyName = 'id';
	
		$grid->addColumn('id', 'Id')->addFilter();
		$grid->addColumn('amount', 'Amount')->addFilter();
		$grid->addColumn('datetime', 'Date')->addDateFilter();
		
		return $grid;
	}

** my issue is to be able to show only exact driver payments **
is it somehow possible to pass from template id of driver to createComponentDriversFeePaymentsGrid methos, e.g. @{widget` driversFeePaymentsGrid, driverId}

**Comment by romansklenar** [comment]
Hi @armenmargaryan, development of this lib was stopped 7 years ago and I don't remember Nette that well so this is probably not the answer you want but I'd suggest you to use some other up-to-date components available which are still maintained and gets support from their authors: https://componette.com/search/?q=datagrid

**Comment by armenmargaryan** [comment]
Ok thanks anyway for response
